language: node_js
node_js:
- "7.10.0"  # nodejs的版本
branches:
  only:
  - master  # 设置自动化部署的源码分支

# ------------------------------------------------
# 下面是你的Token加密信息，不要替换
# ------------------------------------------------
env:
  global:
    secure: qoGU4ateflROIPgGizyz1N1uyfDXvkhhjj+xonEbB30xjnVjuGDnhoWgnflEibIhj9AP5cBi7zFm5bIPwqO81BgBMIBFBpA09UESWjt98H9/JfwtzylM66lcYhcB+kGdpSlRbNlrYtBgB9KblhbaIiKC0YSDofmAxMBoGRSiFqWlDKuvk3MZ1+8mTZEW0xTB6KQmkghUzQntHsuSFHADOTEGi4SWMPYW7VSR+ResVAQbQfGa6Q3J/B5LU+wHOg6Zjj96HgYIyCpA8e+poB7b5M4P9OpsMwEqbltItQhWNQ0z3+6tpUqGSPPhhefvPlJmZaEOb9ugJUki9/fFnOlihkfkjDU8Tsci18LmmmuFU0wH7L52H61nGlNH3AeXeayzaOakLxFwtm0QtDewG5p9yIaSC2pP9t/+eWjOD0sA6clWk8HRBaA+Ir6bKLM2Hm+wH7UaXZ/owUbmeLWv/ZOA2G9ttgJyT8eoz8dOZY72kXP2GBuqjU7ph3mflooX/TxWHUKfBVYkeJlNZl+iOjEPaVQnSSD9ca/6GvB30+M17gSVlH2G616xvSe/sSwCfUv6X/IUBaXMHzaYUphzM52ltg+v4QVMr+P0j1vyWVXPvB+3bHkwjn+VrSIef/2NTFOsECLHH1QoJ1KtBKKJayIgQORhOk8nvDLl+iTRWEv73Nc=

before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "jxv007"
- git config --global user.email jxv007@163.com 
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~git@github.com:jxv007/Blog.git~https://${7537af8b24470f11ab1d395d473a5c3793c22d12}:x-oauth-basic@github.com/jxv007/Blog.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy